version: '3.8'

services:
  node-app:
    build:
      context: .
      dockerfile: node.dockerfile
    environment:
      - DB_USER=system                       # Oracle DB username
      - DB_PASSWORD=tiger    # Oracle DB password
      - DB_CONNECTION_STRING=host.docker.internal:1521/orcl  # Use the correct Oracle DB port (1521)
    ports:
      - "3000:3000"                          # Expose the application port