name: Check for API Keys in JavaScript Files

on:
  push:
    branches:
      - maste
  pull_request:
    branches:
      - master

jobs:
  scan-js-secrets:
    name: Scan for API Keys in JavaScript Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Snyk
        run: npm install -g snyk

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Find JavaScript Files
        run: git ls-files '*.js' > js-files.txt

      - name: Run Snyk on JavaScript Files
        run: xargs -a js-files.txt snyk code test --severity-threshold=high --json --sarif | tee snyk_report.sarif

      - name: Upload Snyk Report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk_report.sarif
